# Generated by Django 2.0.5 on 2019-12-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=50, null=True)),
                ('VehicleNo', models.CharField(max_length=80, null=True)),
                ('Radius', models.CharField(max_length=50, null=True)),
                ('CurrentLocation', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
