# Generated by Django 2.0.5 on 2019-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0002_geofence_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='CenterLocation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
