# Generated by Django 2.0.5 on 2019-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helpcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, null=True)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('How_can_we_help_you', models.CharField(choices=[('App Crashes', 'App Crashes'), ('Feedback', 'Feedback'), ('Problems on live tracking', 'Problems on live tracking'), ('Wrong datas in reports', 'Wrong datas in reports'), ('Problems in Graphs', 'Problems in Graphs'), ('Problems in geofence', 'Problems in geofence')], max_length=100, null=True)),
                ('message', models.TextField(max_length=100, null=True)),
                ('comments', models.CharField(max_length=80, null=True)),
                ('time', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
