# Generated by Django 2.0.5 on 2019-12-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='longtude',
            new_name='longitude',
        ),
    ]
