# Generated by Django 2.0.5 on 2019-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, null=True)),
                ('Ticket_Name', models.CharField(max_length=50, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=100, null=True)),
                ('Description', models.TextField(max_length=80, null=True)),
                ('time', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
