# Generated by Django 2.0.5 on 2019-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_addtickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=50, null=True)),
                ('Vehicleno', models.CharField(max_length=80, null=True)),
                ('Radius', models.CharField(max_length=50, null=True)),
                ('PresentLocation', models.CharField(max_length=50, null=True)),
                ('Bounds', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddTickets',
        ),
        migrations.DeleteModel(
            name='AddDevice',
        ),
    ]
