# Generated by Django 2.0.5 on 2019-12-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_auto_20191130_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geofence',
        ),
    ]
